### ISSUE TITLE
 string indices must be integers

### ISSUE THREAD

**Issue by cz-git666** [yiming-zh/DPL#1]
"model.py", line 185, 
Why bert_out_origin = bert_out[:, 0:max(l), :] is wrong?
TypeError: string indices must be integers
How to solve the problem?

**Comment by yiming-zh** [comment]
Hello, I can't reproduce this bug. 
Did you modify other parts or can you provide more information?

It looks like the type of the variable "l" is wrong. Please check whether it remains 'torch.LongTensor'.
The following are other code locations related to variable "l":

> "loader.py", line 120, "length = len(tok)"
> "loader.py", line 214, "length, index = torch.LongTensor(batch[index]), index+1"

Hope this information helps you.

**Comment by yiming-zh** [comment]
Hello, I find where the bug is.

Please use the transformers==2.9.1
The 4.26.0 transformers will lead to this Error.
